/// Escuelas profesionales de la UNSAAC, escritas de forma oficial y sin
/// errores de ortografia, para que los datos de beca salgan correctos.
/// Se usan en el formulario de registro (selecciona, no escribe).
const List<String> carrerasUnsaac = [
  'Administración',
  'Antropología',
  'Arqueología',
  'Arquitectura',
  'Biología',
  'Ciencias de la Comunicación',
  'Contabilidad',
  'Derecho',
  'Ecoturismo',
  'Economía',
  'Educación Física',
  'Educación Inicial',
  'Educación Primaria',
  'Educación Secundaria: Ciencias Naturales',
  'Educación Secundaria: Ciencias Sociales',
  'Educación Secundaria: Lengua y Literatura',
  'Educación Secundaria: Matemática, Física e Informática',
  'Enfermería',
  'Farmacia y Bioquímica',
  'Física',
  'Historia',
  'Ingeniería Agroindustrial',
  'Ingeniería Agronómica',
  'Ingeniería Agropecuaria',
  'Ingeniería Ambiental',
  'Ingeniería Civil',
  'Ingeniería de Minas',
  'Ingeniería Eléctrica',
  'Ingeniería Electrónica',
  'Ingeniería Forestal',
  'Ingeniería Geológica',
  'Ingeniería Informática y de Sistemas',
  'Ingeniería Mecánica',
  'Ingeniería Metalúrgica',
  'Ingeniería Petroquímica',
  'Ingeniería Química',
  'Lingüística',
  'Matemática',
  'Medicina Humana',
  'Medicina Veterinaria',
  'Nutrición Humana',
  'Obstetricia',
  'Psicología',
  'Química',
  'Trabajo Social',
  'Turismo',
  'Zootecnia',
  'Otra (especificar)',
];
